### ISSUE TITLE
Please add support for Groups

### ISSUE THREAD

**Issue by mikeblakeuk** [Vtek/PowerBI.Api.Client#31]
Hi,

Please add support for 
http://docs.powerbi.apiary.io/#reference/groups

Thanks

**Comment by Vtek** [comment]
Feature is avaible on v1.2 branch. You can use the classic library to test it : https://github.com/Vtek/PowerBI.Api.Client/tree/v1.2/dist/Classic

Beware, due to this feature, the Api url define in configuration must be changed. In the 1.1 version it was : 
<Api Url="https://api.powerbi.com/v1.0/myorg/datasets" />

Datasets is now remove in the url :
<Api Url="https://api.powerbi.com/v1.0/myorg" />

**Comment by Vtek** [comment]
1.2 alpha version avaible on NuGet (Pre version).
Please read the 1.2 wiki page : https://github.com/Vtek/PowerBI.Api.Client/wiki/Version-1.2-alpha

A++
Sylvain
